### ISSUE TITLE
No "Deposit Confirmation" Box

### ISSUE THREAD

**Issue by phzarif85** [ConcealNetwork/conceal-desktop#115]
Desktop wallet stuck, no "Deposit Confirmation" box when making a new deposit. Its happens when the wallet been running for more than two days.

Wallet Version: 6.2.1
Windows: Windows 7 Pro

**Comment by cryptokatz** [comment]
@phzarif85 Does the deposit go through?

**Comment by phzarif85** [comment]
No, the QMessageBox::warning "Deposit Confirmation" not appear. Wallet "freeze" can't click anything. So I just kill the program using task manager.

**Comment by krypt0x** [comment]
This issue seems to have been solved. I'm closing this thread. Thanks
