### ISSUE TITLE
Desktop Wallet Needing to be Restored

### ISSUE THREAD

**Issue by ronaldvo** [ConcealNetwork/conceal-desktop#144]
I didn't back up my wallet properly, however it loaded fine 2-3 times over the past couple of days. Today, the wallet did not load and asked me to create new or restore. 

Not sure if it's because it couldn't locate the wallet.wallet file, but was asked to create a ticket here on TG.

I have created a new wallet just fine and backed this one up. The other wallet had nothing in it, so it's not an issue.

**Comment by krypt0x** [comment]
You will need to locate your wallet file manually. Use the file location and load it trough the file browser.

**Comment by krypt0x** [comment]
Good! You could always import your seed/keys to restore a wallet/address. 

I will close this issue. If you need further assistance, please submit a ticket in our help desk portal. 

https://conceal.network/support

Thank you.
