### ISSUE TITLE
Macbook GUI Wallet

### ISSUE THREAD

**Issue by compositesandre** [ConcealNetwork/conceal-desktop#145]
Every time I send a transaction out from my Macbook GUI-Wallet the whole wallet closes and I have to reopen and wait for the whole cache to be rebuilt. The transaction does go fine anyway.

**Comment by krypt0x** [comment]
Hi, could you please give us more details about your set up? Which version of MacOs are you using? What cpu does your machine have? Thanks

**Comment by compositesandre** [comment]
[Screen Shot 2021-07-18 at 08.20.32.png]

If you need more info let me know

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Em terça-feira, 13 de julho de 2021 às 4:58 PM, Øx ***@***.***> escreveu:

**Comment by krypt0x** [comment]
Hi, we can't see the screenshot. Can you please upload it or write down your specs?

**Comment by krypt0x** [comment]
Hi, can you please let us know which macOS version are you using in that device? What about the CPU, can you tell us which processor does your machine have? Thanks

**Comment by compositesandre** [comment]
MacBook Pro (13-inch 2017, Four Thunderbolt 3 Ports)
Processor 3,1 GHz Dual-Core Intel Core i5
Memory 8GB 2133 MHz LPDDR3
Startup Disk Macintosh HD
Graphics Intel Iris Plus Graphics 650 1536MB

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Em quarta-feira, 11 de agosto de 2021 às 5:39 AM, Øx ***@***.***> escreveu:

**Comment by compositesandre** [comment]
macOS Big Sur Version 11.2.3

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Em quarta-feira, 11 de agosto de 2021 às 8:06 AM, altca ***@***.***> escreveu:

**Comment by krypt0x** [comment]
Hi, unfortunately we couldn't replicate this issue. It might happen due to a corrupted wallet file. Could you please be kind enough to create a new wallet file importing your seed/keys and try again? Thanks

**Comment by krypt0x** [comment]
Your specs shouldn't be an issue. There are a few users with the same set up as yours.

**Comment by krypt0x** [comment]
Is there any chance your could search for error messages in your wallet log file?

**Comment by krypt0x** [comment]
@AxVultis developed a new macOS Wallet with extended log writing. Would you be willing to be a betatester? We couldn't replicate your issue and we might catch it this way.

**Comment by compositesandre** [comment]
Can do no problem just send me the link to download the wallet

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 5 de set de 2021 18:30, Øx escreveu:

**Comment by krypt0x** [comment]
Cool! 

Check it out,

https://github.com/AxVultis/conceal-desktop/suites/3682955634/artifacts/89717930

**Comment by krypt0x** [comment]
Issue closed by inactivity.
