### ISSUE TITLE
Password for Desktop Wallet

### ISSUE THREAD

**Issue by ibmacer** [ConcealNetwork/conceal-desktop#146]
Hi, added a contact to my address book, then tried to send funds but the desktop wallet kept asking me for a password....but wouldn't accept the wallet password then I closed the wallet and re-opened and sent using "send funds" and does not ask for password
Is this normal behavior to ask for password when sending funds? anything I should be worried about?
I went in just now and sent funds to that saved address book and it went through without password request
just found it add the desktop wallet asked for password that it wouldn't accept and then doesn't ask for it again when doing the same actions.

I am using v6.4.8

**Comment by krypt0x** [comment]
Hi, this isn't an usual behaviour. We will have a look into this. Thanks

**Comment by krypt0x** [comment]
@AxVultis The "send funds" tab probably will need to check up if the user has a password set up before asking for the password.

**Comment by AxVultis** [comment]
The password prompt is showed only for encrypted wallets. I think the wallet file may be corrupted and that is why it is asking for password.

**Comment by krypt0x** [comment]
This issue seems to have been solved, Thanks
