### ISSUE TITLE
Desktop wallet crash

### ISSUE THREAD

**Issue by m-c-hizzle** [ConcealNetwork/conceal-desktop#147]
The most recent version of the desktop wallet for windows 10 (6.4.8) will crash when sending funds. 
I can reopen the wallet and it will "rebuild the cache" for about 10 minutes and the wallet will then open. Once inside I can see that the transaction has sent.

**Comment by krypt0x** [comment]
Hi, could you please check what error message have you got in the wallet's log file and share it with us?

**Comment by krypt0x** [comment]
This issue has been closed due to inactivity.
