### ISSUE TITLE
Market Information on Dashboard screen auto-refresh or refresh button

### ISSUE THREAD

**Issue by MrSlinkyman** [ConcealNetwork/conceal-desktop#149]
**Is your feature request related to a problem? Please describe.**
I keep the Conceal Wallet desktop application running all the time because I don't want to wait for the chain to refresh whenever I want to see my balance.  I also like to see Market information about CCX.  However, the market information seems to only refresh on open.

**Describe the solution you'd like**
I would like the market data to refresh periodically with a datestamp saying when it last refreshed and the exchange data it is using. 

**Describe alternatives you've considered**
If auto refresh is not viable, provide a button that can be used to refresh the data manually.

**Additional context**
![image](https://user-images.githubusercontent.com/3213052/124309388-7fd3fb00-db1f-11eb-82f8-899036fca249.png)
Notice the market data only goes till 6/26 but today is 7/2

**Comment by AxVultis** [comment]
Hello @MrSlinkyman 

Thanks for your suggestion, we will have a look to add this feature in a future release.

**Comment by krypt0x** [comment]
This feature will be included in our next release. Thank you very much .
