### ISSUE TITLE
Desktop app won't open anymore 

### ISSUE THREAD

**Issue by Nacretr** [ConcealNetwork/conceal-desktop#150]
Hello there,
Since I couldn't save the wallet file, I was opening the wallet by entering the key (Copy and Paste). The Synchronization process had reached 90%, but the Desktop wallet does not open anymore (in Admin mode). Boot Logo appears for 1-2 seconds then shuts down. I've deleted and reinstalled a couple of times but it won't open. What can I do? Thanks. 

-OS: Windows 10
-Version : ccx-desktop-win64-v6.4.8

![Ekran görüntüsü 2021-07-02 223016](https://user-images.githubusercontent.com/83866464/124321058-b2b0da00-db85-11eb-9a17-5ee57088489f.jpg)

**Comment by AxVultis** [comment]
Hello @Nacretr

The blockchain data seems to be corrupted on your computer which is causing Conceal Desktop to close itself.

Try to delete blockchain data and sync from scratch.
Make sure you have a backup of your seed/keys before proceeding.
You can follow this guide: https://conceal.network/wiki/doku.php?id=faq#qhow_to_delete_blockchain_data_and_sync_from_scratch

**Comment by Nacretr** [comment]
Hello again,
There is no "conceal" folder in "C:\Users\<yourusername>\AppData\Roaming\", only "conceal-lite-wallet" folder belonging to lite wallet. 

![Ekran görüntüsü 2021-07-12 171301](https://user-images.githubusercontent.com/83866464/125326183-6fefbe80-e34a-11eb-80be-480261ec574f.jpg)


I uninstall the wallet, I delete the ProgramFiles(x86)\conceal wallet folder.
![Ekran görüntüsü 2021-07-12 185308](https://user-images.githubusercontent.com/83866464/125326295-8d248d00-e34a-11eb-85fc-56a2b079c0d0.jpg)


I cleaned regedit myself.
![Ekran görüntüsü 2021-07-12 191101](https://user-images.githubusercontent.com/83866464/125326531-d2e15580-e34a-11eb-8c3d-d319e1ee4f97.jpg)
![Ekran görüntüsü 2021-07-12 191230](https://user-images.githubusercontent.com/83866464/125326561-db399080-e34a-11eb-983f-017a79a9373a.jpg)
........

I installed 6.4.8 and ran it as administrator without rebooting (because I'm mining), but it still won't open. 
Thanks.
I'm sorry I don't speak English, google translate.

**Comment by Nacretr** [comment]
Also, the wallet folder is not created in "C:\Users<yourusername>\AppData\Roaming" after installation.

**Comment by krypt0x** [comment]
Hi, would you be kind enough to answer some questions?

What language is your Windows 10 running? Does your username includes any special characters? Do you have at least 4GB free on your system? Is conceal Desktop able to bypass your anti-virus and firewall?

And a hint...
Let's suppose your windows username is "Nacretr" the block data files will be stored in `C:\Users\Nacretr\AppData\Roaming\conceal`. Mind that `AppData` folder usually is hidden.

**Comment by Nacretr** [comment]
Hi again and apologies.

- My operating system is Windows 10 Turkish.
- Yes my username contains special characters.
- I have free space on my system (200gb free hdd+ 16gb ram)
- No hidden desktop. 
- Windows firewall is on. 

Earlier the wallet was working. Tnx.

**Comment by Nacretr** [comment]
I managed to open the wallet. The problem was that there was a special character in my username. During the installation of the program, a new username (consisting of complex letters) was created under the "user" folder and uploaded the "AppData" folder there. I cleaned and reinstalled this folder and it worked. Sorry for the translation. Thanks everyone.

**Comment by krypt0x** [comment]
Hi, you are welcome. We're glad it worked at your end. We will make some enhancements in the next release to avoid these situations. Thank you very much.
