### ISSUE TITLE
To big dont fit in screen 1900x1600

### ISSUE THREAD

**Issue by t3chnomusic** [ConcealNetwork/conceal-desktop#167]
**Describe the bug**
Application is to big to use buttons.
Unusable

**To Reproduce**
On first start.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by krypt0x** [comment]
Can you provide more details about your setup? OS? Resolution of the device? Etc.

**Comment by krypt0x** [comment]
Without any details about your device it isn't possible to go further... I'm closing this issue. Thanks
