### ISSUE TITLE
SHA 256 doesn't match windows desktop 

### ISSUE THREAD

**Issue by auroracoin** [ConcealNetwork/conceal-desktop#180]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AxVultis** [comment]
Hello @auroracoin, could you please give us more detail about which file / version you checked, and where was it downloaded?
We checked the latest releases and all sha256sums matched.
Thanks

**Comment by auroracoin** [comment]
https://github.com/ConcealNetwork/conceal-desktop/releases/tag/6.6.3
When I extract the file and right click to read the sha256 they don't match. Windows

**Comment by AxVultis** [comment]
The sha256 is provided for the zip file, you do not have to extract the file to check it.

**Comment by auroracoin** [comment]
Oooo ok I was checking it wrong. Thank you Ok now. Thx for your help. :)
