### ISSUE TITLE
Do not allow un-synchronized remote nodes

### ISSUE THREAD

**Issue by travis1234** [ConcealNetwork/conceal-desktop#50]
When testing the automatic remote node feature in the wallet I was assigned to a remote node that wasn't fully synced.

After restarting the wallet and connecting to a fully synced remote node my wallet had to be fully re-scanned from block 0.

Not really a bug, just annoying from the users perspective.

**Comment by krypt0x** [comment]
Hi Travis1234, we have taken your suggestion in consideration and it will be included in the next update. Thank you
