### ISSUE TITLE
Can we get a linux appimage of the wallet please?

### ISSUE THREAD

**Issue by treepi3** [ConcealNetwork/conceal-desktop#51]
Question says it all. Shouldnt be hard to do as far as I know.

**Comment by krypt0x** [comment]
We will have a look at it as soon as we have some spare time. Thanks

**Comment by treepi3** [comment]
> We will have a look at it as soon as we have some spare time. Thanks

Cool. I'm running Solus Linux and I cant run the Ubuntu file like I was able to when I was using Manjaro. This is the only thing keeping me from investing into CCX actually. Once I have a wallet that works for me, I'll be buying some.

Also, do you have an Android wallet? And are transactions private by default?

**Comment by taeguscromis** [comment]
An Android wallet is in the works. We also have a cloud wallet accessible from any browser. Please join us on Discord where we can answer all your questions. You can find all info and links on our web page: https://conceal.network/

**Comment by treepi3** [comment]
> An Android wallet is in the works. We also have a cloud wallet accessible from any browser. Please join us on Discord where we can answer all your questions. You can find all info and links on our web page: https://conceal.network/

I got the ubuntu 18.04 release running on my solus distro. Just had to make a .desktop file for it is all.

**Comment by krypt0x** [comment]
Great! I am closing this request. Thanks to all participants.
