### ISSUE TITLE
Unable to use GUI wallet, crashes at start(Arch Linux)

### ISSUE THREAD

**Issue by mavrent** [ConcealNetwork/conceal-desktop#74]
On Arch Linux x64 using either wallet:

[user@desktop Downloads]$ ./CONCEAL-GUI
Loaded 0 known transfer(s)
CONCEAL-GUI: /root/conceal-desktop/cryptonote/src/CryptoNoteCore/Currency.cpp:899: CryptoNote::difficulty_type CryptoNote::Currency::nextDifficultyLWMA3(std::vector<long unsigned int>, std::vector<long unsigned int>) const: Assertion `timestamps.size() == cumulative_difficulties.size() && timestamps.size() <= N+1' failed.
Aborted (core dumped)
[user@desktop Downloads]$ 

This happened around the time the wallet synchronized to 100000 blocks, now it crashes every time it opens.

**Comment by cryptokatz** [comment]
@mavrent I believe you will need to compile it for Arch Linux. We haven't had an in-house binary for it in some time.

**Comment by mavrent** [comment]
Up until this one the dozen or so app images and binaries made for Ubuntu I've ran on Arch have just worked, no fuss. There's plenty of us Arch users running Ubuntu binaries no problem.
Arch does have the user repository for things that need to be built just for Arch - this isn't in it yet.
Yeah, seems I'll have to learn to manually build for Arch if this doesn't match the other apps made for Ubuntu in terms of Arch compatibility.

**Comment by mavrent** [comment]
I'd like this to work out-of-box on Arch like other apps, but I'm not opposed to learning to build something. Reading up on doing this, it's said I need to follow the author's instructions.
So far I've installed boost, now the make command gets this far:

[user@desktop conceal-desktop-5.4.1]$ make
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- The C compiler identification is GNU 9.1.0
-- The CXX compiler identification is GNU 9.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
fatal: not a git repository (or any of the parent directories): .git
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Boost: /usr/include (found suitable version "1.69.0", minimum required is "1.55") found components:  date_time filesystem program_options regex serialization system thread chrono atomic 
CMake Error: File /home/user/Build/conceal/conceal-desktop-5.4.1/cryptonote/src/version.h.in does not exist.
CMake Error at CMakeLists.txt:42 (configure_file):
  configure_file Problem configuring file


-- Configuring incomplete, errors occurred!
See also "/home/user/Build/conceal/conceal-desktop-5.4.1/build/release/CMakeFiles/CMakeOutput.log".
See also "/home/user/Build/conceal/conceal-desktop-5.4.1/build/release/CMakeFiles/CMakeError.log".
make: *** [Makefile:17: cmake-release] Error 1

what now?

**Comment by mavrent** [comment]
Following the instructions gets me this far now:

[user@desktop conceal-desktop]$ make build-release
mkdir -p build/release
cd build/release && cmake -D CMAKE_BUILD_TYPE=Release ../..
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/lib64/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/boost_date_time-1.71.0/boost_date_time-config.cmake

  but it set boost_date_time_FOUND to FALSE so package "boost_date_time" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_date_time.so.1.71.0 (shared, Boost_USE_STATIC_LIBS=ON)

  * libboost_date_time.a (shared runtime, Boost_USE_STATIC_RUNTIME=ON)

Call Stack (most recent call first):
  /usr/lib64/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/share/cmake-3.15/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:33 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/user/Build/conceal-desktop/build/release/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:17: cmake-release] Error 1
[user@desktop conceal-desktop]$

**Comment by mavrent** [comment]
Downgraded boost to 1.69, wallet now compiles and runs on Arch Linux.
